### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by KayWw** [bravepipeproject/BravePipeExtractor#106]

**Comment by KayWw** [comment]
## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.23.3-2.1.2
* __OS:__ Linux Android 13 - 33
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Parameter specified as non-null is null: method org.schabi.newpipe.local.feed.service.FeedLoadService$onStartCommand$2.accept, parameter error
	at org.schabi.newpipe.local.feed.service.FeedLoadService$onStartCommand$2.accept(Unknown Source:7)
	at org.schabi.newpipe.local.feed.service.FeedLoadService$onStartCommand$2.accept(FeedLoadService.kt:98)
	at io.reactivex.rxjava3.internal.observers.BiConsumerSingleObserver.onSuccess(BiConsumerSingleObserver.java:56)
	at io.reactivex.rxjava3.internal.operators.single.SingleDoOnSubscribe$DoOnSubscribeSingleObserver.onSuccess(SingleDoOnSubscribe.java:77)
	at io.reactivex.rxjava3.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:81)
	at io.reactivex.rxjava3.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:123)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7924)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

```
</details>
<hr>

**Comment by evermind-zz** [comment]
https://github.com/TeamNewPipe/NewPipe/pull/10229
I'll try to merge this.

**Comment by evermind-zz** [comment]
https://github.com/bravenewpipe/BraveNewPipeLegacy/issues/3
