### ISSUE TITLE
Video playback stopped working [Rumble]

### ISSUE THREAD

**Issue by longestmt** [bravepipeproject/BravePipeExtractor#123]
I was able to watch rumble videos recently as Wednesday but since then playback is returning the "frowny face" error screen (image attached). If it's anything like the youtube newpipe then it's probably a change on the Rumble side.

Thanks for building a great app!
![Screenshot_20240302_081852_BraveNewPipe](https://github.com/bravenewpipe/NewPipeExtractor/assets/1509654/1df17533-db66-4562-8124-459b5d65278f)

**Comment by gpilot24** [comment]
Same for me yesterday....Thumbnail screen populates and search is working, any attempt to play video fails.

## Exception
* __User Action:__ requested stream
* __Request:__ https://rumble.com/v2gaj22-wild-video-pro-and-anti-trumo-supporters-nearly-comes-to-blows.html
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ Rumble
* __Version:__ 0.26.1-2.1.7
* __OS:__ Linux Android 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
java.net.ProtocolException: Too many follow-up requests: 21
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:127)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
	at org.schabi.newpipe.DownloaderImpl.execute(DownloaderImpl.java:184)
	at org.schabi.newpipe.extractor.downloader.Downloader.get(Downloader.java:77)
	at org.schabi.newpipe.extractor.downloader.Downloader.get(Downloader.java:32)
	at org.schabi.newpipe.extractor.services.rumble.extractors.RumbleStreamExtractor.onFetchPage(RumbleStreamExtractor.java:399)
	at org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:60)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:77)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:72)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:119)
	at org.schabi.newpipe.util.ExtractorHelper.$r8$lambda$YTHJjScxCJNO1LTCqs3IKy35iyY(ExtractorHelper.java:0)
	at org.schabi.newpipe.util.ExtractorHelper$$ExternalSyntheticLambda4.call(R8$$SyntheticClass:0)
	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4855)
	at io.reactivex.rxjava3.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4855)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5377)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:16013)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5377)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4855)
	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:644)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

```
</details>
<hr>

**Comment by evermind-zz** [comment]
They introduced some url redirecting and cookies that need to be set by BraveNewPipe. I've added a cookie manager library that fixes this issue. But as the cookies are handled globally (and not per service) I have to investigate more if this solution do not interfere with the other services:
Here is a test version:
[bravenewpipe-rumble-fix.zip](https://github.com/bravenewpipe/NewPipeExtractor/files/14471187/bravenewpipe-rumble-fix.zip)

**Comment by rogerdc** [comment]
Does the cookie library keep track of the sites the cookies are for? In that case, global or per-site shouldn't matter.

**Comment by gpilot24** [comment]
> They introduced some url redirecting and cookies that need to be set by BraveNewPipe. I've added a cookie manager library that fixes this issue.

So far so good on Rumble.  Nice work. Switched over to YT, played something, and back to Rumble.  Still OK!  I'll test some more soon.

Curious as to the "Kitkat" in the filename?

**Comment by evermind-zz** [comment]
> > They introduced some url redirecting and cookies that need to be set by BraveNewPipe. I've added a cookie manager library that fixes this issue.
> 
> So far so good on Rumble. Nice work. Switched over to YT, played something, and back to Rumble. Still OK! I'll test some more soon.

Great!

> 
> Curious as to the "Kitkat" in the filename?

I've ditched BraveNewPipeLegacy which was based on code before TeamNewPipe dropped support for Kitkat. But with every other release it (BraveNewPipeLegacy) was harder to maintain -- Now Kitkat support will be integrated as a flavor into BraveNewPipe

@rogerdc 
> Does the cookie library keep track of the sites the cookies are for? In that case, global or per-site shouldn't matter.

yes that is what I want to check too

**Comment by gpilot24** [comment]
May have a stream issue....its early, just fyi, thanks for a really cool app!

## Exception
* __User Action:__ play stream
* __Request:__ Player error[type=ERROR_CODE_PARSING_CONTAINER_UNSUPPORTED] occurred while playing https://rumble.com/v4guze0
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ Rumble
* __Version:__ 0.26.1-2.1.7
* __OS:__ Linux Android 9 - 28
<details><summary><b>Crash log </b></summary><p>

```
com.google.android.exoplayer2.ExoPlaybackException: Source error
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:644)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:614)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:193)
	at android.os.HandlerThread.run(HandlerThread.java:65)
Caused by: com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (FlvExtractor, FlacExtractor, WavExtractor, FragmentedMp4Extractor, Mp4Extractor, AmrExtractor, PsExtractor, OggExtractor, TsExtractor, MatroskaExtractor, AdtsExtractor, Ac3Extractor, Ac4Extractor, Mp3Extractor, AviExtractor, JpegExtractor) could read the stream.
	at com.google.android.exoplayer2.source.BundledExtractorsAdapter.init(BundledExtractorsAdapter.java:92)
	at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1017)
	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)

```
</details>
<hr>

**Comment by longestmt** [comment]
It's working for me now.

**Comment by gpilot24** [comment]
Me, too.  Just a comment, the most recent bravenewpipe version is working on Rumble, meaning the version in the repo, not the rumble-fix.zip version. The -fix version is still working.   Whether the installation of the rumble-fix version affected the repo version (added resources) or not, I don't think it would, coincidence??

**Comment by evermind-zz** [comment]
Rumble had a temporary glitch and 0.26.1-2.1.7 is working fine again. I will still add this cookie fix for Rumble as to me this glitch seems intentional.

**Comment by gpilot24** [comment]
Great!!

Where can one send a paypal donation??
--

**Comment by gpilot24** [comment]
> Great!! Where can one send a paypal donation?? -
