### ISSUE TITLE
Kitkat  v0.26.1-2.1.9 test version

### ISSUE THREAD

**Issue by evermind-zz** [bravepipeproject/BravePipeExtractor#124]
With Release v0.26.1-2.1.9 there is a Kitkat flavor that is based on current code v0.26.1 NewPipe code.

This is only a test version. I could not really test it on hardware. It only was tested on emulator.
Therefore it will not migrate any data from previous installs. It installs in parallel to any BraveNewPipe installation.
This will change if I get feedback  that it is working more or less properly.

All problems please enter here in this bug entry or if it is too big create a extra bug entry.

**Comment by marcel263** [comment]
Dear,the app no longer functions

when loading subscriptions:

`java.lang.NoSuchMethodError: No virtual method toString(Z)Ljava/lang/String; in class Lokhttp3/Cookie; or its super classes (declaration of 'okhttp3.Cookie' appears in base.apk)`

**Comment by evermind-zz** [comment]
> Dear,the app no longer functions
> 
> when loading subscriptions:
> 
> `java.lang.NoSuchMethodError: No virtual method toString(Z)Ljava/lang/String; in class Lokhttp3/Cookie; or its super classes (declaration of 'okhttp3.Cookie' appears in base.apk)`

Please be more specific. I can import subscription and I can fetch the feed. What hardware/software platform are you running?

**Comment by marcel263** [comment]
> > Dear,the app no longer functions
> > when loading subscriptions:
> > `java.lang.NoSuchMethodError: No virtual method toString(Z)Ljava/lang/String; in class Lokhttp3/Cookie; or its super classes (declaration of 'okhttp3.Cookie' appears in base.apk)`
> 
> Please be more specific. I can import subscription and I can fetch the feed. What hardware/software platform are you running?

This was the only exception in the error log.

Nothing works, there is no connection to Youtube possible. Trending is not loading, videos shared to the app don't play. Cleared data. Newly installed BraveNewPipe 0.26.1-2.1.8 on an Android 13 Samsung device.

**Comment by evermind-zz** [comment]
> > > Dear,the app no longer functions
> > > when loading subscriptions:
> > > `java.lang.NoSuchMethodError: No virtual method toString(Z)Ljava/lang/String; in class Lokhttp3/Cookie; or its super classes (declaration of 'okhttp3.Cookie' appears in base.apk)`
> > 
> > 
> > Please be more specific. I can import subscription and I can fetch the feed. What hardware/software platform are you running?
> 
> This was the only exception in the error log.
> 
> Nothing works, there is no connection to Youtube possible. Trending is not loading, videos shared to the app don't play. Cleared data. Newly installed BraveNewPipe 0.26.1-2.1.8 on an Android 13 Samsung device.

Thank you. I did overlook this one. Next release should work!

**Comment by Phmurrph** [comment]
Greetings. 🙋
Icons appearing black when using dark or black theme making them barely noticeable:
![BraveNewPipe_guithubreport](https://github.com/bravenewpipe/NewPipeExtractor/assets/140580407/b51040b3-da42-4ee9-96ca-7129159b2305)

Also, 'Brightness', 'Volume', 'Pause' and 'Play' icons display in very low resolution on fullscreen.

**Comment by Phmurrph** [comment]
A bug I found on the first video I tried crashed the app:

## Exception
* __User Action:__ play stream
* __Request:__ Player error[type=ERROR_CODE_IO_UNSPECIFIED] occurred while playing https://www.youtube.com/watch?v=mKdjycj-7eE
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ YouTube
* __Version:__ 0.26.1-2.1.9
* __OS:__ Linux Android 4.4.2 - 19
<details><summary><b>Crash log </b></summary><p>

```
com.google.android.exoplayer2.ExoPlaybackException: Source error
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:644)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:620)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:146)
	at android.os.HandlerThread.run(HandlerThread.java:61)
Caused by: java.io.IOException: java.lang.Exception: java.lang.NullPointerException
	at org.schabi.newpipe.player.mediasource.FailedMediaSource.maybeThrowSourceInfoRefreshError(FailedMediaSource.java:129)
	at com.google.android.exoplayer2.source.MaskingMediaPeriod.maybeThrowPrepareError(MaskingMediaPeriod.java:156)
	at com.google.android.exoplayer2.source.MaskingMediaPeriod.maybeThrowPrepareError(MaskingMediaPeriod.java:154)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1024)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:502)
	... 3 more
Caused by: java.lang.Exception: java.lang.NullPointerException
	at org.schabi.newpipe.player.playback.MediaSourceManager.lambda$getLoadedMediaSource$7(MediaSourceManager.java:469)
	at org.schabi.newpipe.player.playback.MediaSourceManager.$r8$lambda$7wkrzYpwfZdms79okpk8_MCaW4U(MediaSourceManager.java:0)
	at org.schabi.newpipe.player.playback.MediaSourceManager$$ExternalSyntheticLambda5.apply(R8$$SyntheticClass:0)
	at io.reactivex.rxjava3.internal.operators.single.SingleOnErrorReturn$OnErrorReturn.onError(SingleOnErrorReturn.java:55)
	at io.reactivex.rxjava3.internal.operators.single.SingleMap$MapSingleObserver.onError(SingleMap.java:70)
	at io.reactivex.rxjava3.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:61)
	at io.reactivex.rxjava3.internal.operators.single.SingleDoOnError$DoOnError.onSuccess(SingleDoOnError.java:52)
	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.onSuccess(SingleSubscribeOn.java:68)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeToSingle$ToSingleMaybeSubscriber.onSuccess(MaybeToSingle.java:83)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onNext(FlowableElementAtMaybe.java:80)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:136)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:16013)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5377)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4855)
	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:644)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:841)
Caused by: java.lang.NullPointerException
	at j$.util.Comparator$-CC.lambda$comparing$77a9974f$1(SourceFile)
	at j$.util.Comparator$$ExternalSyntheticLambda5.compare(SourceFile)
	at j$.util.Comparator$-CC.$private$lambda$thenComparing$36697e65$1(SourceFile)
	at j$.util.Comparator$$ExternalSyntheticLambda1.compare(SourceFile)
	at java.util.TimSort.binarySort(TimSort.java:261)
	at java.util.TimSort.sort(TimSort.java:186)
	at java.util.Arrays.sort(Arrays.java:2011)
	at j$.util.stream.SortedOps$SizedRefSortingSink.end(SourceFile)
	at j$.util.stream.AbstractPipeline.copyInto(SourceFile)
	at j$.util.stream.AbstractPipeline.wrapAndCopyInto(SourceFile)
	at j$.util.stream.ReduceOps$ReduceOp.evaluateSequential(SourceFile)
	at j$.util.stream.AbstractPipeline.evaluate(SourceFile)
	at j$.util.stream.ReferencePipeline.collect(SourceFile)
	at org.schabi.newpipe.util.ListHelper.getFilteredAudioStreams(ListHelper.java:324)
	at org.schabi.newpipe.player.resolver.VideoPlaybackResolver.resolve(VideoPlaybackResolver.java:81)
	at org.schabi.newpipe.player.Player.sourceOf(Player.java:2009)
	at org.schabi.newpipe.player.playback.MediaSourceManager.lambda$getLoadedMediaSource$6(MediaSourceManager.java:433)
	at org.schabi.newpipe.player.playback.MediaSourceManager.$r8$lambda$TrlxO9KUeHA8dnLgSgaWsUWa_Ko(MediaSourceManager.java:0)
	at org.schabi.newpipe.player.playback.MediaSourceManager$$ExternalSyntheticLambda4.apply(R8$$SyntheticClass:0)
	at io.reactivex.rxjava3.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:58)
	... 23 more

```
</details>
<hr>

Thats all I have for now.
I'll keep testing.

Edit: I forgot to mention that this has been the only video I couldn't play so far, other than that it's been fine.

**Comment by evermind-zz** [comment]
> A bug I found on the first video I tried crashed the app:
> 
> ## Exception
> ....
> 
> Edit: I forgot to mention that this has been the only video I couldn't play so far, other than that it's been fine.

I've tested this on [Brave]NewPipe (non-kitkat) version and could not play it either.
