### ISSUE TITLE
Rumble: Some videos don't play

### ISSUE THREAD

**Issue by schmittkw** [bravepipeproject/BravePipeExtractor#147]
Happens on pixel with grapheneOS.

I can't say for certain what the failing videos have in common.

Log from phone:
-------------------------------------
com.google.android.exoplayer2.ExoPlaybackException: Source error
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:644)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:614)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.os.HandlerThread.run(HandlerThread.java:68)
Caused by: com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (FlvExtractor, FlacExtractor, WavExtractor, FragmentedMp4Extractor, Mp4Extractor, AmrExtractor, PsExtractor, OggExtractor, TsExtractor, MatroskaExtractor, AdtsExtractor, Ac3Extractor, Ac4Extractor, Mp3Extractor, AviExtractor, JpegExtractor) could read the stream.
	at com.google.android.exoplayer2.source.BundledExtractorsAdapter.init(BundledExtractorsAdapter.java:92)
	at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1017)
	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

**Comment by evermind-zz** [comment]
I experienced similar. The cases I've looked into the video seems to be private..

**Comment by timur-g** [comment]
Can you list videos that don't play?
There were some fixes in 0.27.

**Comment by schmittkw** [comment]
I could list a few videos but they work now. It's typically a live feed from earlier in the day and when I go to replay it later in the same day it won't work.

Yahoo Mail: Search, Organize, Conquer 
 
  On Wed, Jul 24, 2024 at 3:12 PM, ***@***.***> wrote:   


Can you list videos that don't play?
There were some fixes in 0.27.

**Comment by bravepipeproject** [comment]
fixed #182
