### ISSUE TITLE
Crashes every time I minimize the app

### ISSUE THREAD

**Issue by jalle007** [bravepipeproject/BravePipeExtractor#166]
## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.27.2-2.3.1
* __OS:__ Linux Redmi/sweet_global2/sweet:13/TKQ1.221114.001/V816.0.6.0.THGMIXM:user/release-keys 13 - 33
<details><summary><b>Crash log </b></summary><p>

```
android.os.BadParcelableException: Parcelable encountered IOException writing serializable object (name = org.schabi.newpipe.extractor.channel.ChannelInfo)
	at android.os.Parcel.writeSerializable(Parcel.java:2751)
	at android.os.Parcel.writeValue(Parcel.java:2517)
	at android.os.Parcel.writeValue(Parcel.java:2316)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1265)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1802)
	at android.os.Bundle.writeToParcel(Bundle.java:1362)
	at android.os.Parcel.writeBundle(Parcel.java:1334)
	at android.os.Parcel.writeValue(Parcel.java:2433)
	at android.os.Parcel.writeValue(Parcel.java:2323)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1265)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1802)
	at android.os.Bundle.writeToParcel(Bundle.java:1362)
	at android.os.Parcel.writeBundle(Parcel.java:1334)
	at android.os.Parcel.writeValue(Parcel.java:2433)
	at android.os.Parcel.writeValue(Parcel.java:2323)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1265)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1802)
	at android.os.Bundle.writeToParcel(Bundle.java:1362)
	at android.os.Parcel.writeBundle(Parcel.java:1334)
	at android.os.Parcel.writeValue(Parcel.java:2433)
	at android.os.Parcel.writeValue(Parcel.java:2323)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1265)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1802)
	at android.os.Bundle.writeToParcel(Bundle.java:1362)
	at android.os.Parcel.writeBundle(Parcel.java:1334)
	at android.os.Parcel.writeValue(Parcel.java:2433)
	at android.os.Parcel.writeValue(Parcel.java:2323)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1265)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1802)
	at android.os.Bundle.writeToParcel(Bundle.java:1362)
	at android.os.Parcel.writeBundle(Parcel.java:1334)
	at android.os.Parcel.writeValue(Parcel.java:2433)
	at android.os.Parcel.writeValue(Parcel.java:2323)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1265)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1802)
	at android.os.Bundle.writeToParcel(Bundle.java:1362)
	at android.os.Parcel.writeBundle(Parcel.java:1334)
	at android.os.Parcel.writeValue(Parcel.java:2433)
	at android.os.Parcel.writeValue(Parcel.java:2323)
	at android.os.BaseBundle.dumpStats(BaseBundle.java:1874)
	at android.os.BaseBundle.dumpStats(BaseBundle.java:1911)
	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:152)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8503)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
Caused by: java.io.NotSerializableException: org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeChannelExtractor
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1240)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1620)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1581)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1490)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1620)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1581)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1490)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:354)
	at java.util.ArrayList.writeObject(ArrayList.java:955)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1079)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1568)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1490)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1620)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1581)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1490)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1620)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1581)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1490)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:354)
	at android.os.Parcel.writeSerializable(Parcel.java:2746)
	... 49 more

```
</details>
<hr>

**Comment by timur-g** [comment]
App doesn't crash for me in general. Happened once I could not start, resolved with clearing. You may try to clear cache, then storage. Hopefully you may close.
Also, this is reported under Extractor but seems like App.
