### ISSUE TITLE
ISSUE: Pressing the "Content Filter" Crashes the app on Bravenewpipe legacy

### ISSUE THREAD

**Issue by MikaelaMuller** [bravepipeproject/BravePipeExtractor#169]
Crash log

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ PH
* __Content Language:__ en-PH
* __App Language:__ en_PH
* __Service:__ none
* __Version:__ 0.27.2-2.3.1
* __OS:__ Linux Android 4.4.2 - 19
<details><summary><b>Crash log </b></summary><p>

```
java.lang.ClassCastException: android.view.ViewGroup$LayoutParams cannot be cast to android.widget.AbsListView$LayoutParams
	at android.widget.ListView.measureScrapChild(ListView.java:1194)
	at android.widget.ListView.measureHeightOfChildren(ListView.java:1276)
	at android.widget.ListPopupWindow.buildDropDown(ListPopupWindow.java:1177)
	at android.widget.ListPopupWindow.show(ListPopupWindow.java:564)
	at android.widget.Spinner$DropdownPopup.show(Spinner.java:1176)
	at android.widget.Spinner.performClick(Spinner.java:685)
	at android.view.View$PerformClick.run(View.java:19270)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:146)
	at android.app.ActivityThread.main(ActivityThread.java:5602)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
	at dalvik.system.NativeStart.main(Native Method)

```
</details>
<hr>

![Screenshot_2024-12-13-09-49-45](https://github.com/user-attachments/assets/a3072500-817d-44c2-80ef-b4cb2d562667)
![Screenshot_2024-12-13-09-51-38](https://github.com/user-attachments/assets/41563206-4ace-4810-96b0-b74c5e22f9a6)

**Comment by evermind-zz** [comment]
fixed in https://github.com/bravenewpipe/NewPipe/releases/tag/v0.27.5-2.3.3
