### ISSUE TITLE
New rumble ui broke channel page

### ISSUE THREAD

**Issue by ghost** [bravepipeproject/BravePipeExtractor#67]
Opening this as a attempt to gather all current rumble issues that ive found currently since the new rumble web ui broke some functionality in the app. 

**issues are rumble specific only**

-Opening a channel under subscription tab fails
-Going to a channel page fails (through name on video) ^related to abovd
-Loading feed of recent videos skips rumble based videos

What works (at this time of writing)
-searching videos
-playing videos opened through search only 

I dont know if this fork is still maintained but its been the best of both sites bundled together that I use daily and i wish I had the ability to help with these issues but eitherway I thankyou for all the work done so far to have made this possible in the first place.

**Comment by json-by-jason** [comment]
Second the above comment. BNP's the only non-web-app I know of that allows browsing Rumble without being forced to make an account, and services like yours that bypass these sorts of gates have more value than they get credit for.

Included the error message in case it might help narrow things down: [Bluestacks 5.9.600.1001 running 64-bit Nougat]

## Exception
* __User Action:__ requested channel
* __Request:__ Start loading: https://rumble.com/c/SaltyCracker
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ Rumble
* __Version:__ 0.24.1-2.0.0
* __OS:__ Linux Android 7.1.1 - 25
<details><summary><b>Crash log </b></summary><p>

```
org.schabi.newpipe.extractor.exceptions.ParsingException: Could not get channel id: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.jsoup.nodes.Node.attr(java.lang.String)' on a null object reference
	at org.schabi.newpipe.extractor.services.rumble.RumbleParsingHelper.extractSafely(RumbleParsingHelper.java:76)
	at org.schabi.newpipe.extractor.services.rumble.extractors.RumbleChannelExtractor.getId(RumbleChannelExtractor.java:57)
	at org.schabi.newpipe.extractor.channel.ChannelInfo.getInfo(ChannelInfo.java:69)
	at org.schabi.newpipe.extractor.channel.ChannelInfo.getInfo(ChannelInfo.java:55)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getChannelInfo$4(ExtractorHelper.java:128)
	at org.schabi.newpipe.util.ExtractorHelper$$ExternalSyntheticLambda5.call(D8$$SyntheticClass)
	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15868)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:644)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)

```
</details>
<hr>

**Comment by json-by-jason** [comment]
<s>
For some reason, the debug app that the dev set up in #57 allows account pages to render correctly; on top of this it adds comment support and a background player!
Edit: The first time I tried loading an account page it gave an error page; clicking the "Retry" button resolved this
</s>

I spoke too early, this was me gushing about a player that had still been open to the YouTube page. For the record, the debug apk still does not add comments, nor does it fix the rendering with Rumble profiles.

**Comment by evermind-zz** [comment]
I'll have a look at the rumble issues.

@json-by-jason Rumble comments are not supported as you have to have an account to see them - or am I wrong?

**Comment by powline99** [comment]
Bitchute's Comments also do not work.

**Comment by evermind-zz** [comment]
> Bitchute's Comments also do not work

@powline99 Could you please be more specific and report to issue #57?

**Comment by json-by-jason** [comment]
My mistake, I completely misread the text of 57.

Thanks very much for doing what you do
