### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by killerrook** [bravepipeproject/BravePipeExtractor#95]
Steps to reproduce:-
1. Launch bravenewpipe app
2. Experience crash (random in nature)

Bug report:-
## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ IN
* __Content Language:__ en-IN
* __App Language:__ en_IN
* __Service:__ none
* __Version:__ 0.25.1-2.1.0
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{243afd8 u0 com.github.bravenewpipe/org.schabi.newpipe.player.PlayerService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2005)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7660)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

```
</details>
<hr>

**Comment by evermind-zz** [comment]
Wontfix: This is already reported upstream: https://github.com/TeamNewPipe/NewPipe/issues/9070
